name: Build & Generate APK

on:
  pull_request:
    branches:
      - 'master'

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup google-services.json
        env:
          GOOGLE_SERVICES_FILE: ${{ secrets.GOOGLE_SERVICES_FILE }}
        run: echo $GOOGLE_SERVICES_FILE > app/google-services.json
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Save artifact
        uses: actions/upload-artifact@v1
        with:
          name: debug-app
          path: app/build/outputs/apk/debug/app-debug.apk
