# This is a basic workflow to help you get started with Actions

name: Instrumented tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]
        arch: [x86]

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup google-services.json
        env:
           GOOGLE_SERVICES_FILE: ${{ secrets.GOOGLE_SERVICES_FILE }}
        run: echo $GOOGLE_SERVICES_FILE > app/google-services.json
        
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: default
          arch: ${{ matrix.arch }}
          profile: Nexus 6
          script: ./gradlew connectedAndroidTest --stacktrace
